---
title: "About Us"
---


‘ፈለገ ዮርዳኖስ መንፈሳዊ ጠቅላላ ማኅበር’ በምዕራብ አርሲ ሀገረ ስብከት ሻሸመኔ ከተማ የተቋቋመ ሲሆን በኢትዮጵያ ኦርቶዶክስ ተዋሕዶ ቤተክርስቲያን የማህበራት ማደራጃና መምሪያ ህጋዊ ምዝገባ በማድረግ እውቅና የተሰጠው ለመንፈሳዊ አገልግሎት የተሰማራ ማኅበር ነው። ማኅበሩ የኢትዮጵያ ኦርቶዶክስ ተዋሕዶ ቤተክርስቲያንን ዶግማ፣ ቀኖና፣ ታሪክ እና ትውፊት ጠብቆ የሚንቀሳቀስ፣ ለቤተክርስቲያን አስተዳደራዊ አሠራር ተገዢ የሆነ፣ ከአድሎአዊነት፣ ከምንፍቅና፣ ከዘር፣ ከጎሳ የጸዳ፣ ነጻ እና ገለልተኛ መንፈሳዊ (ሃይማኖታዊ) ማኅበር ነው። በመሆኑም ማኅበሩ የኢትዮጵያ ኦርቶዶክስ ተዋሕዶ ቤተክርስቲያን ዶግማ፣ ቀኖና፣ ታሪክ እና ትውፊት ለማስጠበቅ ከሚመለከታቸው የቤተክርስቲያን መዋቅሮች ጋር በቅንጅት የሚሰራ ሲሆን አስፈላጊውንም ድጋፍ ያደርጋል። ማኅበሩ የተቋቋመው በማኅበሩ ስም የሚገኝን ማንኛውንም ትርፍ ለአባላቱ ለማከፋፈል ሳይሆን ለትርፍ ያልተቋቋመ የበጎ ፍቃድ አገልግሎት ተቋም ባህርይ ያለው ነው።

የማኅበሩ የአገልግሎት ክልል ሰፊ ሲሆን በአዲስ አበባ፣ በምስራቅ አርሲ፣ በባሌ፣ በምዕራብ ጉራጌ፣ በጉጂ፣ ቦረና፣ በሲዳማ፣ በወላይታ፣ በጋሞጎፋ፣ በሰሜን ሸዋ፣ ዳላስ (አሜሪካ)፣ ካሊፎርኒያ (አሜሪካ)፣ በደቡብ አፍሪካ እና አውስትራሊያ ባሉ አህጉረ ስብከቶች ለማገልገል የተቋቋመ ነው። እንደ አስፈላጊነቱ ወደፊት ሌሎች አህጉረ ስብከቶችን በማካተት አገልግሎቱን ለማስፋት ጥረት ያደርጋል።

ማኅበሩ ከተቋቋመበት ጊዜ አንስቶ የሚሰጣቸውን መንፈሳዊ አገልግሎቶች መምራት እና ማስተባበር በሚያስችሉ መለስተኛ እና አመታዊ ዕቅዶች ሲሰራ ቆይቷል። በኢትዮጵያ ኦርቶዶክስ ተዋሕዶ ቤተክርስቲያን የማህበራት ማደራጃና መምሪያ ህጋዊ ዕውቅና በማግኘቱ ምክንያት የማኅበሩን የዕድገት ደረጃ በሚመጥን ስትራቴጂያዊ ዕቅድ መመራት አስፈላጊ ሆኖ በመገኘቱ፣ ይህ የመጀመሪያው የአምስት ዓመት (2018-2022) ስትራቴጂያዊ ዕቅድ ግቦችን፣ ዓላማዎችን፣ ስትራቴጂዎችንና ተግባራትን ለማካተት ተዘጋጅቷል። ይህ ስትራቴጂያዊ ዕቅድ ቀደም ሲል የተተገበሩትን የማኅበሩን መለስተኛ እና አመታዊ ዕቅዶች አፈጻጸም ግምት ውስጥ ያስገባ ሲሆን፣ ማኅበሩ በአዲስ የእድገት አቅጣጫ ላይ መሆኑን በመገንዘብ አዳዲስ የአገልግሎት መስኮች ላይ ትኩረት ማድረግ እንዳለበት ታሳቢ ተደርጓል።

## Vision

በመንፈሳዊነት መርህ የሚመራ፣ በማኅበራዊና ኢኮኖሚያዊ አቅሙ የዳበረ ኦርቶዶክሳዊ ማኅበረሰብ ተፈጥሮ ማየት

## Mission

የኢትዮጵያ ኦርቶዶክስ ተዋሕዶ ቤተ ክርስቲያን ሐዋርያዊ ተልዕኮን መሠረት ባደረጉ መንፈሳዊ፣ ማኅበራዊና ኢኮኖሚያዊ አገልግሎቶች አማካኝነት ለማኅበሩ አባላት፣ ምእመናንና የቤተ ክርስቲያን ተቋማት ቀልጣፋ፣ ውጤታማና ተደራሽ አገልግሎት መስጠት

## Our Values

- ፈሪሃ እግዚአብሔር

- እምነት 

- አገልጋይነት 

- መንፈሳዊነት 

- ታማኝነት 

- ፍቅር 

- እኩልነት 

- ፍትሃዊነት 

- ሥርዓተ ቤተ ክርስቲያንን ማክበር

- ቅድስና
