---
title: "አባል ስለመሆን"
---


ታላቁን መንፈሳዊ ተልዕኮ ለማገዝ የማኅበራችን አባል እንዲሆኑ ጥሪ ቀርቦልዎታል! የፈለገ ዮርዳኖስ መንፈሳዊ ጠቅላላ ማኅበር አባል ለመሆን የኢትዮጵያ ኦርቶዶክስ ተዋሕዶ ቤተ ክርስቲያን አካል መሆንዎ ብቻ በቂ ነው።

 

### የማኅበሩ አባል በመሆን የሚያገኟቸው ጥቅሞች፦

- መንፈሳዊ ሕይወትዎን ለማሳደግ የሚያስችሉ ትምህርቶችን እና ምክሮችን በላቀ ሁኔታ ያገኛሉ፤
  
- ከበርካታ መንፈሳዊ አባቶች፣ ወንድሞችና እህቶች ጋር ጥልቅ ኅብረት ለመፍጠር የሚያስችል ስብስብ አካል ይሆናሉ፤
  
- ከማኅበሩ አባላት እና ባለድርሻ አካላት ጋር ማኅበራዊና ኢኮኖሚያዊ ትስስር ለመፍጠር ምቹ ሁኔታዎች ያገኛሉ፤
  
- በመንፈሳዊ ጉዞዎች ላይ የመሳተፍ፣ እንዲሁም ከወንድሞችና እህቶች የመንፈሳዊ ሕይወት አኗኗርና የተግባር ልምድ የመቀሰም ዕድል ያገኛሉ፤
  
- በማኅበሩ ውስጥ አባልና አገልጋይ በመሆን የዘመናዊ አስተዳደርና አሰራር ስልቶች አቅምዎን ያዳብራሉ፤
  
- የክርስትና ሕይወትን ዕለት ዕለት በመለማመድ፣ መንግስተ ሰማያትን ለመውረስ የሚያበቃ መልካም ምግባርን ይለማመዱበታል።

 

### አባል በመሆኖዎ የሚሰጡት ግልጋሎት፦

- በእግዚአብሔር በተሰጠዎት ጸጋና በረከት ቤተክርስቲያንንና ምዕመናንን ያገለግላሉ፤

- የቤተክርስቲያንን ዶግማ፣ ቀኖና፣ ትውፊት፣ ሥርዓትና ክብር ለትውልድ እንዲተላለፍ አስተዋጽኦ ያደርጋሉ፤

- በበጎ አድራጎትና እርዳታ ሥራዎች ይሳተፋሉ፤

- የወንጌል ስርጭት፣ የመንፈሳዊ አገልግሎት ተደራሽነትና ሐዋርያዊ ተልእኮ እንዲስፋፋ የበኩሎትን አስተዋጽኦ ያደርጋሉ፤
  
- በተሰጠዎት መክሊትና ባሎት ክህሎት ማኅበሩን ያገለግላሉ።

 

እነኝህን አግለግሎቶች ለማግኘት እና ለመስጠት የማኅበራችን ፈለገ ዮርዳኖስ መንፍሳዊ ጠቅላላ ማኅበር ዓባል ይሆኑ ዘንድ በእግዚያብሔር ሥም በአክብሮት እንጋብዘዎታለን!  
